# 리뷰 정리
- 파일 불러오기
- (상품명, 태그, 태그 개수) 가지는 DataFrame 구성하기
- 태그 개수 당 상품 개수 체크
- 태그 형태소 분석

### TODO:
1. review에 있는 product id의 태그만 사용하기! 나머지는 버리기

In [1]:
import pickle
import pandas as pd
import numpy as np
import glob
from tqdm import tqdm_notebook
from konlpy.tag import Twitter

pd.set_option('display.max_row', 10000)

###  tag 정보 담긴 파일 dictionary로 불러오기

In [2]:
# *.txt 파일 이면 다 불러옴! 주의!
tag_file_list = glob.glob("/Users/hwii/Documents/BOAZ/project/code/크롤링/tags_txt/*.txt")

product_dict = {}
for tag_file in tag_file_list:
    with open(tag_file, 'rb') as f:
        _product_dict = pickle.load(f)
        product_dict.update(_product_dict)
# print(product_dict)

id_tag_dict = {}
taglen_list = []
for id, property in product_dict.items():
    # 지워진 상품 삭제, tag없으면 None대신 빈 list
    if property['title'] is None: continue   
    if property['tags'] is None:
        property['tags'] = []
    taglen_list.append(len(property['tags']))
    property['tags'] = ' '.join(property['tags'])
    id_tag_dict[id] = property['tags']    
#print(id_tag_dict)

### (상품명, 태그, 태그 개수) 가지는 DataFrame 구성하기

In [3]:
df = pd.DataFrame.from_dict(id_tag_dict, orient='index')
df['length'] = taglen_list
df.reset_index(inplace=True)
df.columns = ['product_id', 'all_tags', 'tag_len']
df.head()

   product_id                                           all_tags  tag_len
0  2281750372  10부레깅스 골지레깅스 기모레깅스 겨울레깅스 여자레깅스 무지레깅스 레깅스코디 9부레...       10
1  2429526499  골지레깅스 배색레깅스 여자레깅스 여자레깅스팬츠 기모레깅스 스판레깅스 겨울레깅스 밴딩...       10
2  2233663935  기모레깅스 두줄레깅스 배색레깅스 시보리레깅스 겨울레깅스 하이웨스트레깅스 레깅스팬츠 ...        9
3  2362613543  기모레깅스 여자레깅스 9부레깅스 나팔레깅스 밍크레깅스 겨울레깅스 레깅스코디 편안한코...       10
4  1003434376  피트니스웨어 바지레깅스 기느성바지 기능성레깅스 헬스장운동복 요가팬츠 여자스포츠레깅스...       10

### 태그 개수당 상품 개수

In [4]:
print("df_count_by_taglen: ")
df_count_by_taglen = df.pivot_table(index = 'tag_len', values = 'all_tags',aggfunc = len, margins=True)
df_count_by_taglen

df_count_by_taglen:

         all_tags
tag_len
0          1248.0
1            38.0
2            52.0
3           116.0
4           237.0
5          1534.0
6           251.0
7           430.0
8           577.0
9           946.0
10         6257.0
All       11686.0

In [5]:
#df.to_csv('../tags_clean.csv', encoding='utf-8')

### 태그 처리 방법1: 형태소 분석 후 BOW하기

In [6]:
twitter = Twitter()
list_tags = df['all_tags'].tolist()

# Twitter 기준
useful_pos = ['Adjective', 'Noun', 'Adverb']
total_tag_list = []
useful_tag_list = []

total_tag_unique = set()
useful_tag_unique = set()

for tag in tqdm_notebook(list_tags):
    morphs = twitter.pos(tag)
    useful_tag = [item[0] for item in morphs if item[1] in useful_pos]
    total_tag_list.append(morphs)
    total_tag_unique.update(morphs)
    useful_tag_list.append(useful_tag)
    useful_tag_unique.update(useful_tag)

print("\nUseful pos: ", useful_pos)
print("number of unique morphs: ", len(total_tag_unique))
print("number of unique useful tags: ", len(useful_tag_unique))
print("coverage: %.2f%%" % (len(useful_tag_unique)/len(total_tag_unique)*100))

df2 = df
df2['all_tags'] = useful_tag_list

# taglen 길이 수정
all_tags = df2['all_tags'].tolist()
tag_len_list = [len(tag) for tag in all_tags]
df2['tag_len'] = tag_len_list

df2.head()

HBox(children=(IntProgress(value=0, max=11686), HTML(value='')))

Useful pos:  ['Adjective', 'Noun', 'Adverb']
number of unique morphs:  4047
number of unique useful tags:  3543
coverage: 87.55%

   product_id                                           all_tags  tag_len
0  2281750372  [부, 레깅스, 골지, 레깅스, 기모, 레깅스, 겨울, 레깅스, 여자, 레깅스, 무...       21
1  2429526499  [골지, 레깅스, 배색, 레깅스, 여자, 레깅스, 여자, 레깅스, 팬츠, 기모, 레...       21
2  2233663935  [기모, 레깅스, 줄, 레깅스, 배색, 레깅스, 시, 보리, 레깅스, 겨울, 레깅스...       20
3  2362613543  [기모, 레깅스, 여자, 레깅스, 부, 레깅스, 나팔, 레깅스, 밍크, 레깅스, 겨...       22
4  1003434376  [피트니스, 웨어, 바지, 레깅스, 성, 바지, 기능, 레깅스, 헬스장, 운동복, ...       20

###  태그당 상품 개수 체크(다시)

In [9]:
print("df_count_by_taglen: ")
df_count_by_taglen = df2.pivot_table(index = 'tag_len', values = 'all_tags',aggfunc = len, margins=True)
df_count_by_taglen

df_count_by_taglen:

         all_tags
tag_len
0          1249.0
1            21.0
2            34.0
3            39.0
4           133.0
5           386.0
6           441.0
7           379.0
8           227.0
9           156.0
10          117.0
11          117.0
12          166.0
13          172.0
14          217.0
15          252.0
16          353.0
17          438.0
18          523.0
19          596.0
20          689.0
21          690.0
22          708.0
23          645.0
24          622.0
25          475.0
26          416.0
27          392.0
28          289.0
29          225.0
30          169.0
31          133.0
32           88.0
33           40.0
34           32.0
35           27.0
36            8.0
37           11.0
38            2.0
39            3.0
40            2.0
43            2.0
44            1.0
45            1.0
All       11686.0

### 버린 태그(형태소 분석된 거) 확인

In [10]:
thrown_away = [item for item in unique_morphs if item[1] not in useful_pos]
thrown_away[:10]

NameError: name 'unique_morphs' is not defined

In [11]:
df2.to_csv("/Users/hwii/Documents/BOAZ/project/code/크롤링/tags_txt/tags_processed.csv",
          encoding='utf-8')