In [1]:
import pandas as pd
from collections import Counter

In [10]:
%pwd

'/home/nlp908/data/hwijeen/BOAZ/project/code'

In [13]:
reviews_df = pd.read_csv("../code/크롤링/Reviews_csv/Reviews_merged_processed.csv",
                     index_col=0)
reviews_df.head(100)

,Id,Rating,Review,Review_len_morph
0,2301428333,추천,"[('귀여운', 'Adjective'), ('동전지갑', 'Noun'), ('♡',...",32
1,2301428333,추천,"[('기염', 'Noun'), ('깜', 'Verb'), ('찍', 'Noun'),...",33
2,2301428333,적극추천,"[('너무', 'Noun'), ('이뻐', 'Adjective'), ('요', 'E...",30
3,2301428333,적극추천,"[('강추템', 'Noun'), ('털', 'Noun'), ('빠짐', 'Verb'...",30
4,2301428333,적극추천,"[('너무', 'Noun'), ('귀엽', 'Adjective'), ('습니다', ...",63
5,2301428333,만족,"[('털', 'Noun'), ('부드럽', 'Adjective'), ('고', 'E...",6
6,2301428333,만족,"[('친구', 'Noun'), ('선물', 'Noun'), ('용', 'Noun')...",13
7,2301428333,만족,"[('가방', 'Noun'), ('에', 'Josa'), ('달', 'Noun'),...",7
8,2301428333,만족,"[('선물', 'Noun'), ('주려', 'Verb'), ('고', 'Eomi')...",18
9,2301428333,만족,"[('진짜', 'Noun'), ('너무', 'Noun'), ('너무', 'Noun'...",10
10,2301428333,만족,"[('빠른', 'Adjective'), ('배송', 'Noun'), ('최고', '...",6
11,2429054242,적극추천,"[('좋', 'Adjective'), ('아요', 'Eomi'), ('구매', 'N...",20
12,2429054242,적극추천,"[('좋', 'Adjective'), ('아요', 'Eomi'), ('동전', 'N...",21
13,2429054242,적극추천,"[('좋', 'Adjective'), ('아요', 'Eomi'), ('이어폰', '...",24
14,2429054242,적극추천,"[('굳', 'Adjective'), ('배송', 'Noun'), ('정말', 'N...",30
15,2429054242,적극추천,"[('예뻐', 'Adjective'), ('요', 'Eomi'), ('배송', 'N...",29
16,2429054242,만족,"[('깜', 'Verb'), ('찍', 'Noun'), ('해', 'Josa'), ...",8
17,2429054242,만족,"[('정말', 'Noun'), ('작네', 'Adjective'), ('요', 'E...",6
18,2429054242,보통,"[('품질', 'Noun'), ('대비', 'Noun'), ('조금', 'Noun'...",15
19,2429054242,만족,"[('좋', 'Adjective'), ('아요', 'Eomi'), ('~~', 'P...",3
20,2429054242,만족,"[('핑크색', 'Noun'), ('샀', 'Verb'), ('는데', 'Eomi'...",19
21,2429054242,만족,"[('만족합', 'Verb'), ('니다', 'Eomi')]",2
22,2757633970,만족,"[('좋', 'Adjective'), ('아요', 'Eomi'), ('^^~', '...",3
23,2757633970,만족,"[('맘', 'Noun'), ('에', 'Josa'), ('드는', 'Verb'),...",25
24,2757633970,만족,"[('소재', 'Noun'), ('가', 'Josa'), ('엄청', 'Adverb...",26
25,2757633970,만족,"[('역시', 'Noun'), ('최고', 'Noun'), ('최고', 'Noun'...",4
26,2757633970,만족,"[('너무', 'Noun'), ('이뻐', 'Adjective'), ('요', 'E...",3
27,2757633970,만족,"[('만족합', 'Verb'), ('니다', 'Eomi')]",2
28,2757633970,보통,"[('만족합', 'Verb'), ('니다', 'Eomi')]",2
29,2757633970,만족,"[('두번째', 'Noun'), ('구매', 'Noun'), ('입니', 'Adje...",8
...,...,...,...,...
70,2522926999,적극추천,"[('맘', 'Noun'), ('에', 'Josa'), ('들어', 'Verb'),...",30
71,2522926999,적극추천,"[('추천', 'Noun'), ('다른', 'Noun'), ('색상', 'Noun'...",30
72,2522926999,적극추천,"[('아주', 'Noun'), ('좋', 'Adjective'), ('음', 'Eo...",28
73,2522926999,만족,"[('밝은', 'Verb'), ('색상', 'Noun'), ('의', 'Josa')...",5
74,2522926999,만족,"[('간편하게', 'Adjective'), ('사용하기', 'Verb'), ('좋'...",4
75,2522926999,만족,"[('배송', 'Noun'), ('도', 'Josa'), ('엄청', 'Adverb...",10
76,2522926999,만족,"[('바로', 'Noun'), ('교환', 'Noun'), ('해주셨', 'Verb...",4
77,2522926999,만족,"[('배송', 'Noun'), ('빠름', 'Adjective'), ('예쁨', '...",3
78,1002194299,적극추천,"[('잘', 'VerbPrefix'), ('받았', 'Verb'), ('어요', '...",45
79,1002194299,적극추천,"[('작고', 'Noun'), ('귀여운', 'Adjective'), ('실제', ...",76
80,1002194299,만족,"[('마음', 'Noun'), ('에', 'Josa'), ('쏙', 'Noun'),...",5
81,1002194299,만족,"[('실버', 'Noun'), ('색상', 'Noun'), ('재구', 'Verb'...",17
82,1002194299,만족,"[('골드', 'Noun'), ('색상', 'Noun'), ('도', 'Josa')...",6
83,1002194299,만족,"[('예쁘', 'Adjective'), ('넉', 'Noun'), ('요', 'Jo...",11
84,2218429430,적극추천,"[('예쁘', 'Adjective'), ('고', 'Eomi'), ('편해', 'A...",37
85,2218429430,만족,"[('너무', 'Noun'), ('이뻐', 'Adjective'), ('요', 'E...",42
86,2218429430,만족,"[('예쁘', 'Adjective'), ('고', 'Eomi'), ('편해', 'A...",8
87,2218429430,만족,"[('잘', 'Verb'), ('받았', 'Verb'), ('습니다', 'Eomi')]",3
88,2218429430,만족,"[('배송', 'Noun'), ('빠르', 'Adjective'), ('고', 'E...",4
89,2218429430,만족,"[('배송', 'Noun'), ('둣', 'Noun'), ('좋', 'Adjecti...",5
90,2218429430,만족,"[('동전', 'Noun'), ('많이', 'Adverb'), ('들어', 'Ver...",9
91,2277693792,만족,"[('정민', 'Noun'), ('깜', 'Verb'), ('찍', 'Noun'),...",10
92,2277693792,만족,"[('생각', 'Noun'), ('보다', 'Josa'), ('크기', 'Noun'...",9
93,2277693792,만족,"[('너무', 'Noun'), ('귀여워', 'Adjective'), ('요', '...",3
94,2277693792,만족,"[('아주', 'Noun'), ('좋', 'Adjective'), ('아요', 'E...",3
95,2000112840,추천안함,"[('추천', 'Noun'), ('안해', 'Noun'), ('요', 'Josa')...",40
96,2000112840,불만,"[('환불', 'Noun'), ('안된', 'Verb'), ('대서', 'Noun'...",27
97,2000112840,만족,"[('생각', 'Noun'), ('보다', 'Josa'), ('많이', 'Adver...",26
98,2000112840,만족,"[('만족합', 'Verb'), ('니다', 'Eomi'), ('~', 'Punct...",3
99,2833626018,불만,"[('가격', 'Noun'), ('거품', 'Noun'), ('이', 'Josa')...",6

In [14]:
reviews_df.pivot_table(index='Review_len_morph', values='Review', aggfunc=len)

                  Review
Review_len_morph
1                    284
2                   5424
3                  19603
4                  17015
5                  11565
6                   8729
7                   6863
8                   5898
9                   5207
10                  4581
11                  3887
12                  3623
13                  3060
14                  2705
15                  2350
16                  2190
17                  1952
18                  1765
19                  1568
20                  1559
21                  1477
22                  1667
23                  2016
24                  2538
25                  3245
26                  3908
27                  4231
28                  4634
29                  4331
30                  4133
...                  ...
237                    1
238                    1
240                    1
241                    2
242                    5
245                    1
246                    2
252                    1
255                    1
257                    1
260                    1
263                    1
268                    1
271                    2
274                    1
276                    1
278                    2
280                    3
291                    1
322                    2
323                    2
330                    1
365                    2
376                    1
413                    1
419                    2
424                    2
439                    1
442                    1
508                    1

[241 rows x 1 columns]

#### 길이

In [16]:
reviews_id = set(reviews['Id'].tolist())
print("review 가져온 상품 개수: %d" % len(reviews_id))

review 가져온 상품 개수: 11186

#### 리뷰 단어

In [93]:
reviews_lists = reviews_df['Review'].tolist()
reviews_list = [eval(review) for review in reviews_lists] 
reviews = [item for review in reviews_list for item in review]
words_counter = Counter(reviews)
words_counter.most_common(10)

[(('요', 'Eomi'), 119371),
 (('.', 'Punctuation'), 68391),
 (('좋', 'Adjective'), 64890),
 (('이', 'Josa'), 64485),
 (('에', 'Josa'), 50055),
 (('도', 'Josa'), 47048),
 (('아요', 'Eomi'), 37162),
 (('가', 'Josa'), 36606),
 (('은', 'Josa'), 35252),
 (('네요', 'Eomi'), 34434)]

In [100]:
print("리뷰에 포함된 unique word 개수:", len(words_counter))

리뷰에 포함된 unique word 개수: 39233

#### 만족도별 리뷰 개수

In [89]:
review_count_by_rating = reviews_df.pivot_table(index = 'Rating', values = 'Review',aggfunc = len, margins=True)
review_count_by_rating['%'] = review_count_by_rating['Review']/184963*100
review_count_by_rating

          Review           %
Rating
만족       56128.0   30.345529
보통       75344.0   40.734633
불만       14439.0    7.806426
적극추천     21484.0   11.615296
추천       13035.0    7.047355
추천안함      4533.0    2.450760
All     184963.0  100.000000

### 리뷰 평균 길이

In [1]:
def get_review_len(df):
    """
    adds review_len column to df
    """
    review_list = df['Review'].tolist()
    review_len_list = [len(review) for review in review_list]
    df['Review_len_morph'] = review_len_list

    avg_review_len = sum(review_len_list) // len(review_len_list)
    print("리뷰 평균 길이(형태소 개수): ", avg_review_len)
    return df

In [ ]:
reviews_all_df = get_review_len(reviews_all_df)
reviews_all_df.head()